"""
review_roi.py

GENERAL ROI REVIEW
==================

Reviews candidate Regions of Interest (ROIs) generated by detect_roi.py.

Workflow:

    roi_config.json
        ↓
    Load candidate ROIs
        ↓
    Display ROI on reference image
        ↓
    Review each ROI
        ↓
    Keep / Reject / Edit
        ↓
    Save confirmed configuration


Keyboard Controls
-----------------

A   Accept current ROI
R   Reject current ROI
E   Edit current ROI manually
N   Next ROI
P   Previous ROI
S   Save current progress
Q   Quit


The final configuration is saved with:

    status = CONFIRMED

Only accepted ROIs are used in later processing stages.
"""


from pathlib import Path
import argparse
import json
import shutil

import cv2
import numpy as np


# ============================================================
# PROJECT PATHS
# ============================================================

PROJECT_DIR = Path(__file__).resolve().parent

DEFAULT_OUTPUT_DIR = PROJECT_DIR / "output"

DEFAULT_CONFIG_PATH = (
    DEFAULT_OUTPUT_DIR
    / "roi_config.json"
)

DEFAULT_SAMPLES_DIR = (
    DEFAULT_OUTPUT_DIR
    / "samples"
)

DEFAULT_CONFIRMED_PATH = (
    DEFAULT_OUTPUT_DIR
    / "confirmed_config.json"
)


# ============================================================
# DISPLAY SETTINGS
# ============================================================

WINDOW_NAME = "ROI Review"

MAX_DISPLAY_WIDTH = 1400

MAX_DISPLAY_HEIGHT = 900

BOX_THICKNESS = 2

FONT_SCALE = 0.7

FONT_THICKNESS = 2


# ============================================================
# COLORS
# ============================================================

COLOR_PENDING = (0, 255, 255)

COLOR_ACCEPTED = (0, 255, 0)

COLOR_REJECTED = (0, 0, 255)

COLOR_SELECTED = (255, 255, 255)


# ============================================================
# JSON HELPERS
# ============================================================

def load_json(
    path
):

    with open(
        path,
        "r",
        encoding="utf-8"
    ) as file:

        return json.load(
            file
        )


def save_json(
    data,
    path
):

    path.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    with open(
        path,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            data,
            file,
            indent=4
        )


# ============================================================
# FIND REFERENCE IMAGE
# ============================================================

def find_reference_image(
    samples_dir
):

    image_extensions = {
        ".jpg",
        ".jpeg",
        ".png",
        ".bmp",
    }

    images = []

    if not samples_dir.exists():

        return None

    for path in samples_dir.iterdir():

        if not path.is_file():
            continue

        if (
            path.suffix.lower()
            not in image_extensions
        ):
            continue

        images.append(
            path
        )

    if not images:

        return None

    return sorted(
        images
    )[0]


# ============================================================
# SCALE IMAGE FOR DISPLAY
# ============================================================

def get_display_scale(
    image
):

    height, width = image.shape[:2]

    scale_x = (
        MAX_DISPLAY_WIDTH
        /
        width
    )

    scale_y = (
        MAX_DISPLAY_HEIGHT
        /
        height
    )

    scale = min(
        scale_x,
        scale_y,
        1.0
    )

    return scale


def resize_for_display(
    image
):

    scale = get_display_scale(
        image
    )

    if scale == 1.0:

        return image.copy(), scale

    height, width = image.shape[:2]

    new_width = int(
        width * scale
    )

    new_height = int(
        height * scale
    )

    resized = cv2.resize(
        image,
        (
            new_width,
            new_height
        )
    )

    return resized, scale


# ============================================================
# DRAW SINGLE ROI
# ============================================================

def draw_roi(
    image,
    roi,
    index,
    total,
    scale
):

    output = image.copy()

    coordinates = roi["roi"]

    x1 = coordinates["x1"]
    y1 = coordinates["y1"]

    x2 = coordinates["x2"]
    y2 = coordinates["y2"]

    review_status = roi.get(
        "review_status",
        "PENDING"
    )

    if review_status == "ACCEPTED":

        color = COLOR_ACCEPTED

    elif review_status == "REJECTED":

        color = COLOR_REJECTED

    else:

        color = COLOR_PENDING

    x1_display = int(
        x1 * scale
    )

    y1_display = int(
        y1 * scale
    )

    x2_display = int(
        x2 * scale
    )

    y2_display = int(
        y2 * scale
    )

    cv2.rectangle(
        output,
        (
            x1_display,
            y1_display
        ),
        (
            x2_display,
            y2_display
        ),
        color,
        BOX_THICKNESS
    )

    label = (
        f"{roi['id']} | "
        f"{review_status}"
    )

    cv2.putText(
        output,
        label,
        (
            x1_display,
            max(
                30,
                y1_display - 10
            )
        ),
        cv2.FONT_HERSHEY_SIMPLEX,
        FONT_SCALE,
        color,
        FONT_THICKNESS,
        cv2.LINE_AA
    )

    info_lines = [

        f"ROI {index + 1}/{total}",

        f"ID: {roi['id']}",

        f"Class ID: {roi.get('class_id', 'N/A')}",

        (
            f"Confidence: "
            f"{roi.get('mean_confidence', 0):.3f}"
        ),

        (
            f"Detections: "
            f"{roi.get('used_detection_count', 0)}"
        ),

        f"Status: {review_status}",

    ]

    y_position = 35

    for line in info_lines:

        cv2.putText(
            output,
            line,
            (
                20,
                y_position
            ),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.65,
            COLOR_SELECTED,
            2,
            cv2.LINE_AA
        )

        y_position += 30

    help_lines = [

        "A Accept",
        "R Reject",
        "E Edit",
        "N Next",
        "P Previous",
        "S Save",
        "Q Quit",

    ]

    help_text = (
        " | ".join(
            help_lines
        )
    )

    height = output.shape[0]

    cv2.putText(
        output,
        help_text,
        (
            20,
            height - 25
        ),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.6,
        COLOR_SELECTED,
        2,
        cv2.LINE_AA
    )

    return output


# ============================================================
# MANUAL ROI EDITOR
# ============================================================

class ROIEditor:

    def __init__(
        self,
        image,
        roi,
        scale
    ):

        self.original_image = image

        self.scale = scale

        self.roi = roi

        coordinates = roi["roi"]

        self.start_x = int(
            coordinates["x1"]
            *
            scale
        )

        self.start_y = int(
            coordinates["y1"]
            *
            scale
        )

        self.end_x = int(
            coordinates["x2"]
            *
            scale
        )

        self.end_y = int(
            coordinates["y2"]
            *
            scale
        )

        self.dragging = False

        self.new_start = None

        self.new_end = None


    def mouse_callback(
        self,
        event,
        x,
        y,
        flags,
        param
    ):

        if event == cv2.EVENT_LBUTTONDOWN:

            self.dragging = True

            self.new_start = (
                x,
                y
            )

            self.new_end = (
                x,
                y
            )


        elif (
            event
            ==
            cv2.EVENT_MOUSEMOVE
            and
            self.dragging
        ):

            self.new_end = (
                x,
                y
            )


        elif (
            event
            ==
            cv2.EVENT_LBUTTONUP
            and
            self.dragging
        ):

            self.dragging = False

            self.new_end = (
                x,
                y
            )


    def get_display_image(
        self,
        display_image
    ):

        output = display_image.copy()

        if (
            self.new_start is not None
            and
            self.new_end is not None
        ):

            cv2.rectangle(
                output,
                self.new_start,
                self.new_end,
                COLOR_SELECTED,
                2
            )

        else:

            cv2.rectangle(
                output,
                (
                    self.start_x,
                    self.start_y
                ),
                (
                    self.end_x,
                    self.end_y
                ),
                COLOR_PENDING,
                2
            )

        cv2.putText(
            output,
            "Draw new ROI with mouse | ENTER confirm | ESC cancel",
            (
                20,
                30
            ),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.65,
            COLOR_SELECTED,
            2,
            cv2.LINE_AA
        )

        return output


# ============================================================
# EDIT ROI
# ============================================================

def edit_roi(
    original_image,
    roi
):

    display_image, scale = (
        resize_for_display(
            original_image
        )
    )

    editor = ROIEditor(
        original_image,
        roi,
        scale
    )

    cv2.namedWindow(
        WINDOW_NAME
    )

    cv2.setMouseCallback(
        WINDOW_NAME,
        editor.mouse_callback
    )

    while True:

        output = (
            editor.get_display_image(
                display_image
            )
        )

        cv2.imshow(
            WINDOW_NAME,
            output
        )

        key = cv2.waitKey(
            20
        ) & 0xFF

        # ENTER
        if key in (
            13,
            10
        ):

            if (
                editor.new_start is not None
                and
                editor.new_end is not None
            ):

                x1_display = min(
                    editor.new_start[0],
                    editor.new_end[0]
                )

                y1_display = min(
                    editor.new_start[1],
                    editor.new_end[1]
                )

                x2_display = max(
                    editor.new_start[0],
                    editor.new_end[0]
                )

                y2_display = max(
                    editor.new_start[1],
                    editor.new_end[1]
                )

                if (
                    x2_display
                    -
                    x1_display
                    < 5
                    or
                    y2_display
                    -
                    y1_display
                    < 5
                ):

                    print(
                        "ROI too small. Draw again."
                    )

                    continue

                roi["roi"] = {

                    "x1":
                        int(
                            x1_display
                            /
                            scale
                        ),

                    "y1":
                        int(
                            y1_display
                            /
                            scale
                        ),

                    "x2":
                        int(
                            x2_display
                            /
                            scale
                        ),

                    "y2":
                        int(
                            y2_display
                            /
                            scale
                        ),

                }

                roi["review_status"] = (
                    "ACCEPTED"
                )

            break

        # ESC
        elif key == 27:

            break

    cv2.setMouseCallback(
        WINDOW_NAME,
        lambda *args: None
    )

    return roi


# ============================================================
# GET REVIEW COUNTS
# ============================================================

def get_review_counts(
    rois
):

    counts = {

        "PENDING":
            0,

        "ACCEPTED":
            0,

        "REJECTED":
            0,

    }

    for roi in rois:

        status = roi.get(
            "review_status",
            "PENDING"
        )

        if status not in counts:

            status = "PENDING"

        counts[status] += 1

    return counts


# ============================================================
# SAVE REVIEW PROGRESS
# ============================================================

def save_review_progress(
    config,
    config_path
):

    counts = get_review_counts(
        config["regions"]
    )

    config["status"] = (
        "IN_REVIEW"
    )

    config["review_summary"] = {

        "pending":
            counts["PENDING"],

        "accepted":
            counts["ACCEPTED"],

        "rejected":
            counts["REJECTED"],

    }

    save_json(
        config,
        config_path
    )

    print()
    print(
        "Review progress saved:"
    )

    print(
        f"  {config_path}"
    )


# ============================================================
# BUILD CONFIRMED CONFIG
# ============================================================

def build_confirmed_config(
    config
):

    accepted_regions = []

    for roi in config["regions"]:

        if (
            roi.get(
                "review_status"
            )
            ==
            "ACCEPTED"
        ):

            accepted_regions.append(
                roi
            )

    confirmed = dict(
        config
    )

    confirmed["status"] = (
        "CONFIRMED"
    )

    confirmed["regions"] = (
        accepted_regions
    )

    confirmed["review_summary"] = {

        "total_candidates":
            len(config["regions"]),

        "accepted":
            len(accepted_regions),

        "rejected":
            sum(
                1
                for roi
                in config["regions"]
                if roi.get(
                    "review_status"
                )
                ==
                "REJECTED"
            ),

    }

    return confirmed


# ============================================================
# MAIN REVIEW FUNCTION
# ============================================================

def review_roi(
    config_path,
    samples_dir,
    confirmed_path
):

    config_path = Path(
        config_path
    ).resolve()

    samples_dir = Path(
        samples_dir
    ).resolve()

    confirmed_path = Path(
        confirmed_path
    ).resolve()

    if not config_path.exists():

        raise FileNotFoundError(
            "\nROI configuration not found:\n"
            f"{config_path}\n"
            "\nRun:\n"
            "  python detect_roi.py\n"
            "first."
        )

    config = load_json(
        config_path
    )

    if "regions" not in config:

        raise ValueError(
            "\nInvalid ROI configuration.\n"
            "Missing key: regions"
        )

    rois = config["regions"]

    if not rois:

        raise RuntimeError(
            "\nNo candidate ROIs found.\n"
            "Check detect_roi.py output."
        )

    reference_image_path = (
        find_reference_image(
            samples_dir
        )
    )

    if reference_image_path is None:

        raise FileNotFoundError(
            "\nNo sample images found:\n"
            f"{samples_dir}\n"
        )

    image = cv2.imread(
        str(reference_image_path)
    )

    if image is None:

        raise RuntimeError(
            "\nCould not load reference image:\n"
            f"{reference_image_path}"
        )

    # ========================================================
    # HEADER
    # ========================================================

    print()
    print("=" * 80)
    print("ROI REVIEW")
    print("=" * 80)

    print()

    print(
        f"Configuration : "
        f"{config_path}"
    )

    print(
        f"Reference image: "
        f"{reference_image_path}"
    )

    print(
        f"Candidate ROIs : "
        f"{len(rois)}"
    )

    print()

    print("Controls:")

    print("  A  Accept ROI")
    print("  R  Reject ROI")
    print("  E  Edit ROI")
    print("  N  Next ROI")
    print("  P  Previous ROI")
    print("  S  Save progress")
    print("  Q  Finish review")

    # ========================================================
    # DISPLAY
    # ========================================================

    display_image, scale = (
        resize_for_display(
            image
        )
    )

    current_index = 0

    cv2.namedWindow(
        WINDOW_NAME,
        cv2.WINDOW_NORMAL
    )

    while True:

        current_roi = (
            rois[current_index]
        )

        output = draw_roi(
            display_image,
            current_roi,
            current_index,
            len(rois),
            scale
        )

        cv2.imshow(
            WINDOW_NAME,
            output
        )

        key = cv2.waitKey(
            0
        ) & 0xFF

        # ----------------------------------------------------
        # ACCEPT
        # ----------------------------------------------------

        if key in (
            ord("a"),
            ord("A")
        ):

            current_roi["review_status"] = (
                "ACCEPTED"
            )

            print(
                f"Accepted: "
                f"{current_roi['id']}"
            )


        # ----------------------------------------------------
        # REJECT
        # ----------------------------------------------------

        elif key in (
            ord("r"),
            ord("R")
        ):

            current_roi["review_status"] = (
                "REJECTED"
            )

            print(
                f"Rejected: "
                f"{current_roi['id']}"
            )


        # ----------------------------------------------------
        # EDIT
        # ----------------------------------------------------

        elif key in (
            ord("e"),
            ord("E")
        ):

            current_roi = edit_roi(
                image,
                current_roi
            )

            rois[current_index] = (
                current_roi
            )

            print(
                f"Updated: "
                f"{current_roi['id']}"
            )


        # ----------------------------------------------------
        # NEXT
        # ----------------------------------------------------

        elif key in (
            ord("n"),
            ord("N"),
            83
        ):

            current_index = (
                current_index
                +
                1
            ) % len(rois)


        # ----------------------------------------------------
        # PREVIOUS
        # ----------------------------------------------------

        elif key in (
            ord("p"),
            ord("P"),
            81
        ):

            current_index = (
                current_index
                -
                1
            ) % len(rois)


        # ----------------------------------------------------
        # SAVE PROGRESS
        # ----------------------------------------------------

        elif key in (
            ord("s"),
            ord("S")
        ):

            save_review_progress(
                config,
                config_path
            )


        # ----------------------------------------------------
        # QUIT
        # ----------------------------------------------------

        elif key in (
            ord("q"),
            ord("Q"),
            27
        ):

            break

    cv2.destroyAllWindows()

    # ========================================================
    # FINAL REVIEW CHECK
    # ========================================================

    counts = get_review_counts(
        rois
    )

    print()
    print("=" * 80)
    print("REVIEW SUMMARY")
    print("=" * 80)

    print()

    print(
        f"Pending : "
        f"{counts['PENDING']}"
    )

    print(
        f"Accepted: "
        f"{counts['ACCEPTED']}"
    )

    print(
        f"Rejected: "
        f"{counts['REJECTED']}"
    )

    # ========================================================
    # CONFIRMATION
    # ========================================================

    if counts["PENDING"] > 0:

        print()
        print(
            "Review is incomplete."
        )

        print(
            "Configuration remains in review."
        )

        save_review_progress(
            config,
            config_path
        )

        return

    if counts["ACCEPTED"] == 0:

        print()
        print(
            "No ROIs were accepted."
        )

        save_review_progress(
            config,
            config_path
        )

        return

    confirmed_config = (
        build_confirmed_config(
            config
        )
    )

    save_json(
        confirmed_config,
        confirmed_path
    )

    print()
    print("=" * 80)
    print("ROI CONFIGURATION CONFIRMED")
    print("=" * 80)

    print()

    print(
        f"Confirmed ROIs: "
        f"{len(confirmed_config['regions'])}"
    )

    print(
        f"Saved to:"
    )

    print(
        f"  {confirmed_path}"
    )

    print()

    print(
        "The confirmed configuration is now ready "
        "for later processing stages."
    )


# ============================================================
# MAIN
# ============================================================

def main():

    parser = argparse.ArgumentParser(
        description=(
            "Review and confirm candidate "
            "Regions of Interest."
        )
    )

    parser.add_argument(
        "--config",
        type=Path,
        default=DEFAULT_CONFIG_PATH,
        help=(
            "Path to roi_config.json generated "
            "by detect_roi.py"
        )
    )

    parser.add_argument(
        "--samples",
        type=Path,
        default=DEFAULT_SAMPLES_DIR,
        help=(
            "Directory containing sample images "
            "generated during ROI discovery."
        )
    )

    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_CONFIRMED_PATH,
        help=(
            "Path for the confirmed ROI configuration."
        )
    )

    args = parser.parse_args()

    review_roi(
        config_path=args.config,
        samples_dir=args.samples,
        confirmed_path=args.output
    )


if __name__ == "__main__":

    main()
